[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.9
padding = { x = 10, y = 8 }

[font]
normal = { family = "Fira Code", style = "Retina" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 11.0
offset = { x = 0, y = 1 }

[cursor]
style = "Underline"
unfocused_hollow = true

[mouse]
hide_when_typing = false

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[colors.primary]
background = "#0D1117"
foreground = "#968C83"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#20111B"
red = "#BE100E"
green = "#858162"
yellow = "#EAA549"
blue = "#426A79"
magenta = "#97522C"
cyan = "#989A9C"
white = "#968C83"

[colors.bright]
black = "#5E5252"
red = "#BE100E"
green = "#858162"
yellow = "#EAA549"
blue = "#426A79"
magenta = "#97522C"
cyan = "#989A9C"
white = "#D5CCBA"
